name: Tests
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: microsoft/playwright-github-action@v1
      - run: yarn test